openapi: 3.0.0
info:
  title: Drift Lapse API
  description: This is the drift-lapse backend for controlling GoPro, Image Tracking, and Emotimo.
  version: v1
tags:
  - name: Emotimo
  - name: GoPro
paths:
  /emotimo/absolute:
    post:
      operationId: AbsoluteOperation_absMoveEmotimo
      summary: Move the emotimo to an absolute position
      description: Send a request to move the Emotimo to an absolute position
      parameters: []
      responses:
        '200':
          description: Operation completed successfully, returns the new absolute position
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveResponse'
        '400':
          description: There was an issue that rejected this operation. See schema for details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RejectedError'
        '422':
          description: There was an issue parsing the response. Generated automagically by Pydantic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIValidationError'
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - Emotimo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbsoluteMoveRequest'
  /emotimo/calibrate:
    post:
      operationId: CalibrateOperation_CalibrateEmotimo
      summary: Calibrate the Emotimo
      description: Calibrates the Emotimo positions. Whatever the current positions are, they are now labelled 0.
      parameters: []
      responses:
        '200':
          description: Operations completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveResponse'
        '422':
          description: There was an issue parsing the response. Generated automagically by Pydantic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIValidationError'
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - Emotimo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /emotimo/configure:
    post:
      operationId: ConfigureOperation_configureEmotimo
      summary: Configure the emotimo
      description: Configure the Emotimo operation
      parameters: []
      responses:
        '200':
          description: Operation completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigureResponse'
        '400':
          description: There was an issue that rejected this operation. See schema for details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RejectedError'
        '422':
          description: There was an issue parsing the response. Generated automagically by Pydantic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIValidationError'
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - Emotimo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigureRequest'
  /emotimo/relative:
    post:
      operationId: RelativeOperation_relMoveEmotimo
      summary: Move the emotimo by a relative amount
      description: Send a request to move the Emotimo by a reletive or delta amount
      parameters: []
      responses:
        '200':
          description: Operation completed successfully, returns the new absolute position
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveResponse'
        '400':
          description: There was an issue that rejected this operation. See schema for details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RejectedError'
        '422':
          description: There was an issue parsing the response. Generated automagically by Pydantic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIValidationError'
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - Emotimo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelativeMoveRequest'
  /gopro/photo:
    post:
      operationId: GoProCamera_photoGoPro
      summary: Take a photo
      description: Send a BLE command to the GoPro to take a photo
      parameters: []
      responses:
        '200':
          description: BLE command sent successfully
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - GoPro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /gopro/timelapse/start:
    post:
      operationId: GoProStartTimelapse_startTimelapseGoPro
      summary: Start Timelapse
      description: Send a BLE command to the GoPro to start recording a timelapse
      parameters: []
      responses:
        '200':
          description: BLE command sent successfully
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - GoPro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /gopro/timelapse/stop:
    post:
      operationId: GoProStopTimelapse_stopTimelapseGoPro
      summary: Stop Timelapse
      description: Send a BLE command to the GoPro to stop recording a timelapse
      parameters: []
      responses:
        '200':
          description: BLE command sent successfully
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - GoPro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /gopro/video/start:
    post:
      operationId: GoProStartVideo_startVideoGoPro
      summary: Start Video
      description: Send a BLE command to the GoPro to start recording a video
      parameters: []
      responses:
        '200':
          description: BLE command sent successfully
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - GoPro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /gopro/video/stop:
    post:
      operationId: GoProStopVideo_stopVideoGoPro
      summary: Stop Video
      description: Send a BLE command to the GoPro to stop recording a video
      parameters: []
      responses:
        '200':
          description: BLE command sent successfully
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Something went wrong with processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
      tags:
        - GoPro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
components:
  schemas:
    APIValidationError:
      type: object
      required:
        - detail
        - body
      properties:
        detail:
          type: string
        body:
          type: string
      description: There was an issue parsing the response. Generated automagically by Pydantic
    AbsoluteMoveRequest:
      type: object
      required:
        - absolute
      properties:
        absolute:
          $ref: '#/components/schemas/Position'
    ConfigureRequest:
      type: object
      properties:
        pulseRate:
          type: integer
    ConfigureResponse:
      type: object
      required:
        - pulseRate
      properties:
        pulseRate:
          type: integer
    InternalError:
      type: object
      required:
        - code
        - body
        - detail
      properties:
        code:
          type: string
          enum:
            - INTERNAL_ERROR
        body:
          type: string
        detail:
          type: string
      description: Something went wrong with processing the request
      example:
        statusCode: 500
        code: INTERNAL_ERROR
        body: There was an internal error processing the request
        detail: A lot of detail to help traceback the error
    MoveResponse:
      type: object
      required:
        - position
      properties:
        position:
          $ref: '#/components/schemas/Position'
    Position:
      type: object
      properties:
        pan:
          type: integer
        tilt:
          type: integer
        slide:
          type: integer
    RejectedError:
      type: object
      required:
        - code
        - detail
        - body
      properties:
        code:
          type: string
          enum:
            - MISSING_FIELD
        detail:
          type: string
        body:
          type: string
      description: There was an issue that rejected this operation. See schema for details
    RelativeMoveRequest:
      type: object
      required:
        - relative
      properties:
        relative:
          $ref: '#/components/schemas/Position'
servers:
  - url: http://localhost:8000
    description: Local Server
    variables: {}
