openapi: 3.0.0
info:
  title: Drift Lapse API
  description: This is the drift-lapse backend for controlling GoPro, Image Tracking, and DF3.
  version: v1
tags:
  - name: Turret
paths:
  /turret/move:
    post:
      operationId: MoveOperation_moveTurret
      summary: Move the turret
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      position:
                        $ref: '#/components/schemas/Position'
                    required:
                      - position
                  - type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
      tags:
        - Turret
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/AbsoluteMoveRequest'
                - $ref: '#/components/schemas/RelativeMoveRequest'
components:
  schemas:
    AbsoluteMoveRequest:
      type: object
      required:
        - absolute
      properties:
        absolute:
          $ref: '#/components/schemas/Position'
    Position:
      type: object
      required:
        - pan
        - tilt
        - slide
      properties:
        pan:
          type: integer
        tilt:
          type: integer
        slide:
          type: integer
    RelativeMoveRequest:
      type: object
      required:
        - relative
      properties:
        relative:
          $ref: '#/components/schemas/Position'
servers:
  - url: http://localhost:8000
    description: Local Server
    variables: {}
