# extends: ../tspconfig.yaml                    # Extend another config file
# emit:                                         # Emitter name
#   - "<emitter-name"
# options:                                      # Emitter options
#   <emitter-name>:
#    "<option-name>": "<option-value>"
# environment-variables:                        # Environment variables which can be used to interpolate emitter options
#   <variable-name>:
#     default: "<variable-default>"
# parameters:                                   # Parameters which can be used to interpolate emitter options
#   <param-name>:
#     default: "<param-default>"
# trace:                                        # Trace areas to enable tracing
#  - "<trace-name>"
# warn-as-error: true                           # Treat warnings as errors

emit:
  - "@typespec/openapi3"
  - "@typespec/json-schema"
options:
  "@typespec/openapi3":
    file-type: "yaml"
    output-file: "openapi-spec.yml"
    emitter-output-dir: "{project-root}/../"
  "@typespec/json-schema":
    file-type: "json"
    int64-strategy: "number"
    bundleId: "models.json"
    emitAllModels: true
    emitAllRefs: true
    

output-dir: "{project-root}/../_generated"       # Configure the base output directory for all emitters